BasisType = {
	VALUE = "VALUE",
	GRADIENT = "GRADIENT",
	GRADIENTVALUE = "GRADIENTVALUE",
	SIMPLEX = "SIMPLEX",
	WHITE = "WHITE",
}

FractalType = {
	FRACTIONALBROWNIANMOTION = "FRACTIONALBROWNIANMOTION",
    RIDGEDMULTI = "RIDGEDMULTI",
    BILLOW = "BILLOW",
    MULTI = "MULTI",
    HYBRIDMULTI = "HYBRIDMULTI",
}

InterpolationType = {
    NONE = "NONE",
    LINEAR = "LINEAR",
    CUBIC = "CUBIC",
    QUINTIC = "QUINTIC",
}